events {}
http {
  server {
    listen 80;

    location /auth/ {
      proxy_pass http://auth-service:8001/;
    }

    location /resource/ {
      proxy_pass http://resource-service:8002/;
    }

    location /reservation/ {
      proxy_pass http://reservation-service:8003/;
    }
  }
}
