input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [event] =~ /auth_failure|rbac_denied|reservation_denied/ {
    mutate { add_tag => ["security_event"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
