apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: sentinelcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: sentinelcloud/reservation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: KEYCLOAK_ISSUER
              value: http://keycloak:8080/realms/sentinelcloud
            - name: KEYCLOAK_JWKS_URL
              value: http://keycloak:8080/realms/sentinelcloud/protocol/openid-connect/certs
            - name: KEYCLOAK_AUDIENCE
              value: sentinelcloud-api
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: sentinelcloud
spec:
  selector:
    app: reservation-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
